---
files:
- path: src/main/kotlin/de/andrena/codingaider/settings/AiderSettingsConfigurable.kt
  readOnly: false
- path: src/main/kotlin/de/andrena/codingaider/settings/AiderSettings.kt
  readOnly: false
- path: src/main/kotlin/de/andrena/codingaider/settings/AiderDefaults.kt
  readOnly: false
- path: build.gradle.kts
  readOnly: false
