@startuml

title Messages Module Data Flow

interface PersistentFilesChangedTopic {
    +onPersistentFilesChanged()
}

class Topic {
    +create(name: String, listener: Class)
}

PersistentFilesChangedTopic ..> Topic : uses

@enduml
